[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "familyhistory"
version = "0.1.0"
description = "Family history web application"
readme = "README.md"
requires-python = ">=3.12"
authors = [
    { name = "Alex Little", email = "alex@alexlittle.net" }
]

dependencies = [
    "django==6.0.7",
    "django-tinymce==5.0.0",
    "mysqlclient==2.2.8",
    "Pillow==12.3.0",
    "sorl-thumbnail==13.1.0",
    "djangorestframework==3.18.0",
    "nh3==0.3.7"
]

# Tell setuptools where to find code and how to determine the version
[tool.setuptools]
package-dir = {"" = "."}

[tool.setuptools.packages.find]
where = ["."]
include = ["familyhistory*"]


[tool.ruff]
extend-exclude = ["*/migrations/*.py"]


# Interrogate settings for checking existence of doc strings
[tool.interrogate]
ignore-init-method = true
ignore-init-module = true
ignore-magic = true
ignore-semiprivate = false
ignore-private = false
ignore-property-decorators = false
ignore-module = false
fail-under = 0
verbose = 2
exclude = ["tests", "docs", "build"]

# pydoclint settings for checking correctness and consistency of docstrings
[tool.pydoclint]
style = "google"
exclude = "tests|docs"


[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "config.settings"
python_files = ["test_*.py"]

[tool.coverage.run]
relative_files = true
source = ["."]
omit = ["*/migrations/*", "*/tests/*", "*/settings*.py", "manage.py", "env/*", "docs/*"]



[dependency-groups]
dev = [
    "pytest==9.1.1",
    "pytest-django==4.14.0",
    "twine==7.0.0",
    "build==1.6.0",
    "wheel==0.48.0",
    "pytest-cov==7.1.0",
    "Sphinx==9.1.0",
    "sphinx_rtd_theme==3.1.0",
    "interrogate==1.7.0",
    "pydoclint==0.9.1",
    "setuptools==84.0.0",
    "djangorestframework-stubs==3.18.1"
]
local = [
    "django-extensions==4.1",
    "Werkzeug==3.1.8",
    "pyOpenSSL==26.4.0"
]
deploy = [
    "mod-wsgi==6.0.6"
]

[tool.uv]
default-groups = ["local", "deploy"]
