sonar.projectKey=alexlittle-github_django-familyhistory
sonar.organization=alexlittle-github
sonar.projectName=familyhistory

sonar.sources=.
sonar.tests=tests

sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml

# exclusions
sonar.exclusions=tests/**,docs/**,**/bootstrap-*-dist/**,**/family-chart-*.*,**/*.png,**/*.ico,**/*.jpg,**/migrations/**
sonar.coverage.exclusions=**/settings*.py,manage.py,**/static/familyhistory/*.js