# Generated by Django 6.0.1 on 2026-01-23 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('birth_surname', models.CharField(blank=True, max_length=100)),
                ('current_surname', models.CharField(blank=True, max_length=100)),
                ('other_surnames', models.JSONField(blank=True, default=list)),
                ('known_as', models.CharField(blank=True, max_length=100)),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('birth_month', models.IntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True)),
                ('birth_day', models.IntegerField(blank=True, null=True)),
                ('birth_is_approximate', models.BooleanField(default=False)),
                ('birth_date_description', models.CharField(blank=True, max_length=100)),
                ('death_year', models.IntegerField(blank=True, null=True)),
                ('death_month', models.IntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True)),
                ('death_day', models.IntegerField(blank=True, null=True)),
                ('death_is_approximate', models.BooleanField(default=False)),
                ('death_date_description', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
            },
        ),
    ]
