# Generated by Django 6.0.1 on 2026-01-24 15:49

import familyhistory.models.person
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familyhistory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, upload_to=familyhistory.models.person.photo_path),
        ),
    ]
