# Generated by Django 6.0.1 on 2026-01-24 16:15

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familyhistory', '0002_person_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('is_father_of', 'is father of'), ('is_mother_of', 'is mother of'), ('is_married_to', 'is married to'), ('in_relationship_with', 'in relationship with')], max_length=100)),
                ('description', tinymce.models.HTMLField()),
                ('start_year', models.IntegerField(blank=True, null=True)),
                ('start_month', models.IntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True)),
                ('start_day', models.IntegerField(blank=True, null=True)),
                ('start_date_is_approximate', models.BooleanField(default=False)),
                ('start_date_description', models.CharField(blank=True, max_length=100)),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('end_month', models.IntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True)),
                ('end_day', models.IntegerField(blank=True, null=True)),
                ('end_date_is_approximate', models.BooleanField(default=False)),
                ('end_date_description', models.CharField(blank=True, max_length=100)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_person', to='familyhistory.person')),
                ('related_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_related_person', to='familyhistory.person')),
            ],
            options={
                'verbose_name': 'Relationship',
                'verbose_name_plural': 'Relationships',
            },
        ),
    ]
