# Generated by Django 6.0.1 on 2026-01-24 17:01

import familyhistory.models.document
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familyhistory', '0004_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', tinymce.models.HTMLField()),
                ('type', models.CharField(choices=[('birth_certificate', 'Birth Certificate'), ('marriage_certificate', 'Marriage Certificate'), ('death_certificate', 'Death Certificate'), ('other', 'Other')], max_length=100)),
                ('type_other', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to=familyhistory.models.document.doc_file_path)),
                ('start_year', models.IntegerField(blank=True, null=True)),
                ('start_month', models.IntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True)),
                ('start_day', models.IntegerField(blank=True, null=True)),
                ('start_date_is_approximate', models.BooleanField(default=False)),
                ('start_date_description', models.CharField(blank=True, max_length=100)),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('end_month', models.IntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True)),
                ('end_day', models.IntegerField(blank=True, null=True)),
                ('end_date_is_approximate', models.BooleanField(default=False)),
                ('end_date_description', models.CharField(blank=True, max_length=100)),
                ('event_involved', models.ManyToManyField(related_name='document_event', to='familyhistory.event')),
                ('person_involved', models.ManyToManyField(related_name='document_people', to='familyhistory.person')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
    ]
