# Generated by Django 6.0.1 on 2026-01-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familyhistory', '0005_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type_other',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
