# Generated by Django 6.0.1 on 2026-01-24 18:43

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familyhistory', '0006_alter_document_type_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
