# Generated by Django 6.0.1 on 2026-01-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familyhistory', '0008_alter_person_options_document_created_at_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='relationship',
            constraint=models.UniqueConstraint(fields=('person', 'type', 'related_person'), name='unique_relationship'),
        ),
    ]
