# Generated by Django 6.0.1 on 2026-01-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familyhistory', '0009_relationship_unique_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_unknown',
            field=models.BooleanField(default=False),
        ),
    ]
