# Generated by Django 6.0.1 on 2026-01-27 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familyhistory', '0011_treecache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treecache',
            name='tree',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
