# Generated by Django 6.0.1 on 2026-01-29 12:38

import django.db.models.deletion
import familyhistory.models.document
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familyhistory', '0012_alter_treecache_tree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=familyhistory.models.document.doc_file_path)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familyhistory.document')),
            ],
            options={
                'verbose_name': 'Document File',
                'verbose_name_plural': 'Document Files',
            },
        ),
    ]
