# Generated by Django 6.0.1 on 2026-01-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familyhistory', '0015_alter_documentfile_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('research', 'Research'), ('birth_certificate', 'Birth Certificate'), ('marriage_certificate', 'Marriage Certificate'), ('death_certificate', 'Death Certificate'), ('obituary', 'Obituary'), ('identity_doc', 'Passport/ID'), ('other', 'Other')], max_length=100),
        ),
    ]
