# Generated by Django 6.0.1 on 2026-01-29 20:39

from django.db import migrations, connection


def add_fulltext_index(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute("""
                       ALTER TABLE familyhistory_person
                           ADD FULLTEXT(first_name, middle_name, birth_surname, second_surname, current_surname, known_as);
                       """)

class Migration(migrations.Migration):

    dependencies = [
        ('familyhistory', '0016_alter_document_type'),
    ]

    operations = [
        migrations.RunPython(add_fulltext_index),
    ]


