# Generated by Django 6.0.7 on 2026-08-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("familyhistory", "0018_person_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="is_deceased",
            field=models.BooleanField(default=False),
        ),
    ]
