# Generated by Django 6.0.7 on 2026-08-15 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familyhistory', '0020_alter_person_is_deceased'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='start_date_description',
            new_name='doc_date_description',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='start_date_is_approximate',
            new_name='doc_date_is_approximate',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='start_day',
            new_name='doc_day',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='start_month',
            new_name='doc_month',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='start_year',
            new_name='doc_year',
        ),
        migrations.RemoveField(
            model_name='document',
            name='end_date_description',
        ),
        migrations.RemoveField(
            model_name='document',
            name='end_date_is_approximate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='end_day',
        ),
        migrations.RemoveField(
            model_name='document',
            name='end_month',
        ),
        migrations.RemoveField(
            model_name='document',
            name='end_year',
        ),
    ]
