# Generated by Django 6.0.7 on 2026-08-28 14:51

import django.core.validators
import familyhistory.models.document
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familyhistory', '0022_alter_document_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfile',
            name='file',
            field=models.FileField(upload_to=familyhistory.models.document.doc_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp', 'tif', 'tiff', 'webp', 'pdf', 'doc', 'docx', 'odt', 'rtf', 'txt', 'csv'])]),
        ),
    ]
