# Generated by Django 6.0.7 on 2026-08-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familyhistory', '0023_alter_documentfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
